"""Context lifecycle contracts and legacy projection adapter."""

from .compatibility import LegacyContextEngineAdapter
from .conformance import assert_context_parity
from .relevance import (
    MEMORY_RELEVANCE_SCHEMA_VERSION,
    MemoryCandidate,
    MemoryScorer,
    RankedMemoryHit,
    WeightedMemoryScorer,
    memory_search,
    rank_memory_candidates,
    tokenize,
)
from .engine import DefaultContextEngine
from .checkpoint import (
    CHECKPOINT_JSON_SCHEMA,
    CHECKPOINT_SCHEMA_VERSION,
    CheckpointEffectRef,
    CheckpointFileRef,
    StructuredContextCheckpoint,
    checkpoint_entry_conflicts,
    parse_checkpoint_json,
    render_checkpoint_message,
)
from .retention import (
    DEFAULT_MAX_RESULT_SHARE,
    RETENTION_SCHEMA_VERSION,
    ToolResultRetention,
    plan_tool_result_retention,
)
from .planner import (
    CONTEXT_PLANNER_SCHEMA_VERSION,
    ContextPlan,
    estimate_text_tokens,
    fingerprint_context,
    plan_context_segments,
)
from .protocol import (
    CONTEXT_PROTOCOL_VERSION,
    BootstrapRequest,
    CommitResult,
    CompactionRequest,
    CompactionResult,
    ContextBudget,
    ContextEngine,
    ContextInput,
    ContextInputKind,
    ContextRequest,
    ContextSegment,
    ContextSegmentKind,
    ContextSnapshot,
    ContextTransform,
    MaintenanceRequest,
    MaintenanceResult,
    TurnOutcome,
)

__all__ = [
    "CONTEXT_PLANNER_SCHEMA_VERSION",
    "CONTEXT_PROTOCOL_VERSION",
    "BootstrapRequest",
    "CommitResult",
    "CompactionRequest",
    "CompactionResult",
    "ContextBudget",
    "ContextEngine",
    "ContextInput",
    "ContextInputKind",
    "ContextPlan",
    "ContextRequest",
    "ContextSegment",
    "ContextSegmentKind",
    "ContextSnapshot",
    "ContextTransform",
    "DefaultContextEngine",
    "LegacyContextEngineAdapter",
    "MaintenanceRequest",
    "MaintenanceResult",
    "TurnOutcome",
    "assert_context_parity",
    "DEFAULT_MAX_RESULT_SHARE",
    "RETENTION_SCHEMA_VERSION",
    "ToolResultRetention",
    "CHECKPOINT_JSON_SCHEMA",
    "CHECKPOINT_SCHEMA_VERSION",
    "CheckpointEffectRef",
    "CheckpointFileRef",
    "StructuredContextCheckpoint",
    "MEMORY_RELEVANCE_SCHEMA_VERSION",
    "MemoryCandidate",
    "MemoryScorer",
    "RankedMemoryHit",
    "WeightedMemoryScorer",
    "checkpoint_entry_conflicts",
    "estimate_text_tokens",
    "fingerprint_context",
    "parse_checkpoint_json",
    "memory_search",
    "plan_context_segments",
    "plan_tool_result_retention",
    "rank_memory_candidates",
    "render_checkpoint_message",
    "tokenize",
]