"""Parent/child Agent execution contracts."""

from .agent_tools import (
    CANCEL_AGENT_NAME,
    QUERY_AGENT_NAME,
    SPAWN_AGENT_NAME,
    CancelAgentTool,
    DelegationToolHandler,
    QueryAgentTool,
    SpawnAgentTool,
    child_run_handle_json,
)
from .coordinator import (
    MAX_DEPTH,
    READ_ONLY_WORKSPACE_MODES,
    ChildRunRecord,
    ChildRunStatus,
    InProcessChildCoordinator,
    PreparedChildSpawn,
    _assemble_child_prompt,
)
from .limits import (
    READ_ONLY_FORBIDDEN_CAPABILITIES,
    READ_ONLY_PROFILE_NAMES,
    ChildCapabilityDecision,
    compute_child_capabilities,
)
from .protocol import (
    DELEGATION_PROTOCOL_VERSION,
    ArtifactRef,
    ChildContextPolicy,
    ChildModelPolicy,
    ChildOutcome,
    ChildOutputSchema,
    ChildStatus,
    DelegationRuntime,
    Finding,
    SpawnSpec,
    UsageSummary,
    WorkspaceMode,
    intersect_capabilities,
)
from .result_projection import (
    CHILD_DELIVERABLE_MAX_CHARACTERS,
    CHILD_SUMMARY_MAX_CHARACTERS,
    ChildResultPolicy,
    project_child_outcome,
)
from .runtime_handler import (
    CapabilityProvider,
    CoordinatorDelegationHandler,
    KernelProvider,
)
from .scheduler import (
    DEFAULT_MAX_CHILDREN_PER_PARENT,
    DEFAULT_MAX_CONCURRENT_CHILDREN,
    ChildBatchLimits,
    ChildBatchSummary,
    InProcessChildScheduler,
)

__all__ = [
    "DELEGATION_PROTOCOL_VERSION",
    "ArtifactRef",
    "ChildContextPolicy",
    "ChildModelPolicy",
    "ChildOutcome",
    "ChildOutputSchema",
    "ChildStatus",
    "DelegationRuntime",
    "Finding",
    "SpawnSpec",
    "UsageSummary",
    "WorkspaceMode",
    "READ_ONLY_FORBIDDEN_CAPABILITIES",
    "READ_ONLY_PROFILE_NAMES",
    "ChildCapabilityDecision",
    "compute_child_capabilities",
    "intersect_capabilities",
    "CHILD_DELIVERABLE_MAX_CHARACTERS",
    "CHILD_SUMMARY_MAX_CHARACTERS",
    "ChildResultPolicy",
    "project_child_outcome",
    "MAX_DEPTH",
    "READ_ONLY_WORKSPACE_MODES",
    "ChildRunRecord",
    "ChildRunStatus",
    "InProcessChildCoordinator",
    "PreparedChildSpawn",
    "_assemble_child_prompt",
    "DEFAULT_MAX_CHILDREN_PER_PARENT",
    "DEFAULT_MAX_CONCURRENT_CHILDREN",
    "ChildBatchLimits",
    "ChildBatchSummary",
    "InProcessChildScheduler",
    "CANCEL_AGENT_NAME",
    "QUERY_AGENT_NAME",
    "SPAWN_AGENT_NAME",
    "CancelAgentTool",
    "DelegationToolHandler",
    "QueryAgentTool",
    "SpawnAgentTool",
    "child_run_handle_json",
    "CapabilityProvider",
    "CoordinatorDelegationHandler",
    "KernelProvider",
]
