"""Version 2 tool contracts and legacy compatibility adapters."""

from .compatibility import LegacyToolAdapter, adapt_legacy_tool
from .conformance import assert_tool_conformance
from .fakes import FakeTool
from .profiles import (
    BUILTIN_CAPABILITY_PROFILES,
    CAPABILITY_PROFILE_SCHEMA_VERSION,
    STANDARD_CAPABILITIES,
    CapabilityContext,
    CapabilityProfile,
    CapabilityProfileResolver,
    InMemoryCapabilityProfileRegistry,
    create_builtin_profile_registry,
    intersect_capability_layers,
    normalize_capabilities,
    validate_capability,
)
from .protocol import (
    TOOL_PROTOCOL_VERSION,
    AgentToolV2,
    ApprovalPolicy,
    IdempotencyPolicy,
    RetryPolicy,
    ToolDefinitionV2,
    ToolEffect,
    ToolExecutionMode,
    ToolExecutionRequest,
    ToolOutcome,
    ToolOutcomeStatus,
    ToolPresentation,
)
from .catalog import (
    TOOL_CATALOG_SCHEMA_VERSION,
    InMemoryToolCatalog,
    ToolCatalog,
    ToolProvenance,
    ToolProvenanceKind,
    ToolRegistration,
    ToolScope,
    ToolSearchQuery,
    ToolSummary,
    ToolSurface,
    ToolSurfaceRequest,
)
from .projection import (
    DEFAULT_ANNOTATION_KEYWORDS,
    PROJECTION_SCHEMA_VERSION,
    DefaultToolSchemaProjection,
    ProjectedToolSchema,
    ProjectionDecision,
    ProviderSchemaProfile,
    SchemaProjectionDiagnostic,
    ToolProjectionReport,
    ToolSchemaProjection,
    project_tool_surface,
    projection_fingerprint,
    schema_fingerprint,
    tool_may_degrade,
)
from .middleware import ToolMiddleware, ToolNext, chain_tool_middleware
from .pipeline import (
    PATH_ARGUMENT_KEYS,
    TOOL_PIPELINE_SCHEMA_VERSION,
    ApprovalHandler,
    AroundToolHook,
    DefaultToolPipeline,
    ResolvedToolCall,
    ToolBatchRequest,
    ToolBatchResult,
    ToolPipeline,
    canonical_path,
)
from .scheduler import (
    TOOL_SCHEDULER_SCHEMA_VERSION,
    ScheduledCall,
    ToolScheduler,
)
from .spill import DEFAULT_SPILL_MARKER, spill_outcome

__all__ = [
    "BUILTIN_CAPABILITY_PROFILES",
    "CAPABILITY_PROFILE_SCHEMA_VERSION",
    "DEFAULT_ANNOTATION_KEYWORDS",
    "DEFAULT_SPILL_MARKER",
    "PATH_ARGUMENT_KEYS",
    "PROJECTION_SCHEMA_VERSION",
    "STANDARD_CAPABILITIES",
    "TOOL_CATALOG_SCHEMA_VERSION",
    "TOOL_PIPELINE_SCHEMA_VERSION",
    "TOOL_PROTOCOL_VERSION",
    "TOOL_SCHEDULER_SCHEMA_VERSION",
    "AgentToolV2",
    "ApprovalHandler",
    "ApprovalPolicy",
    "AroundToolHook",
    "CapabilityContext",
    "CapabilityProfile",
    "CapabilityProfileResolver",
    "DefaultToolPipeline",
    "DefaultToolSchemaProjection",
    "FakeTool",
    "IdempotencyPolicy",
    "InMemoryCapabilityProfileRegistry",
    "InMemoryToolCatalog",
    "LegacyToolAdapter",
    "ProjectedToolSchema",
    "ProjectionDecision",
    "ProviderSchemaProfile",
    "ResolvedToolCall",
    "RetryPolicy",
    "ScheduledCall",
    "SchemaProjectionDiagnostic",
    "ToolBatchRequest",
    "ToolBatchResult",
    "ToolCatalog",
    "ToolDefinitionV2",
    "ToolEffect",
    "ToolExecutionMode",
    "ToolExecutionRequest",
    "ToolMiddleware",
    "ToolNext",
    "ToolOutcome",
    "ToolOutcomeStatus",
    "ToolPipeline",
    "ToolPresentation",
    "ToolProvenance",
    "ToolProvenanceKind",
    "ToolProjectionReport",
    "ToolRegistration",
    "ToolSchemaProjection",
    "ToolScheduler",
    "ToolScope",
    "ToolSearchQuery",
    "ToolSummary",
    "ToolSurface",
    "ToolSurfaceRequest",
    "adapt_legacy_tool",
    "assert_tool_conformance",
    "canonical_path",
    "chain_tool_middleware",
    "create_builtin_profile_registry",
    "intersect_capability_layers",
    "normalize_capabilities",
    "project_tool_surface",
    "projection_fingerprint",
    "schema_fingerprint",
    "spill_outcome",
    "tool_may_degrade",
    "validate_capability",
]